### ISSUE TITLE
Delay in entering/exiting Prompt mode while in windowed mode

### ISSUE THREAD

**Issue by videosmith** [Cuperino/QPrompt-Teleprompter#146]
**Bug Description**
When in windowed mode, selecting 'Start Prompting' or 'Return to Edit Mode'  results in ~2 second delay before text animates or returns to editor, no delay in FullScreen mode.

**Expected behavior**
Windowed mode should mirror FullScreen mode

**Screenshots** (optional)
![info](https://user-images.githubusercontent.com/88691671/213308950-0df0f8d7-8a8c-4c0a-af76-192b1ede120e.png)

**Device information**
 - QPrompt Version: qprompt-v1.1.3-aa79ad5-linux-gcc-x86_64.AppImage
 - Operating System: Debian 11, latest updates

**Comment by Cuperino** [comment]
I've seen this delay before but not only do I not know what causes it. The exact same build can sometimes exhibit this behavior in one system and work perfectly fine on another. Changing Qt and KF5 versions makes no difference in this regard.

When the issue happens to me, it's usually on a VM running Ubuntu 18.04. Because of  this, I've brushed this issue off in the past as a problem with the VM or the operating system. You say you are running on Debian 11, which isn't known to manifest the issue. This leads me to think it may have something to do with hardware or that it may have to do with the way the AppImage's containerization works.

- What CPU model and graphics card (if any) does this computer have?
- Have you tried a different build, Flatpak or Snap?

**Comment by videosmith** [comment]
Dell Inspiron 3521, Intel Dual Core 2nd gen, intel hd graphics 4000 (integrated)
Will try the Arm64 build on a RPi400 next, did not see a SNAP download.
Also will check an older version appimage to see if it manifests this issue.
    On Wednesday, January 18, 2023, 07:48:08 PM EST, Javier O. Cordero Pérez ***@***.***> wrote:  
 
 


I've seen this delay before but not only do I not know what causes it. The exact same build can sometimes exhibit this behavior in one system and work perfectly fine on another. Changing Qt and KF5 versions makes no difference in this regard.

When the issue happens to me, it's usually on a VM running Ubuntu 18.04. Because of this, I've brushed this issue off in the past as a problem with the VM or the operating system. You say you are running on Debian 11, which isn't known to manifest the issue. This leads me to think it may have something to do with hardware or that it may have to do with the way the AppImage's containerization works.
   
   - What CPU model and graphics card (if any) does this computer have?
   - Have you tried a different build, Flatpak or Snap?

**Comment by Cuperino** [comment]
Great idea comparing against an older version.

Snap and Flatpak builds are now available for both x86_64 and arm64 systems. The Snap is using the exact same version of KDE Frameworks as the AppImage. The Flatpak uses a slightly newer version, which has a bug that causes playback controls not to be shown while in full screen.

**Comment by videosmith** [comment]
Are the Flatpak and Snap build available in the SourceForge link?

Delays in all the following versions:
qprompt-main-0fbee21-linux-64-clang.AppImage
qprompt-v1.1-8fc947c-linux-64-clang.AppImage
qprompt-v1.1.1-a873a2e-linux-64-clang.AppImage

No delay in current Arm build.

**Comment by Cuperino** [comment]
All comparisons must be made from within the same computer for this test to work. So far, it may be an issue with the AppImage, but you must compare against the other universal packages to get a better understanding.

Snap and Flatpak installs can be found through pre-configured package managers or through the following links:
- Snap: https://snapcraft.io/qprompt
- Flatpak: https://flathub.org/apps/details/com.cuperino.qprompt

Buttons linking to those pages should also appear at https://qprompt.app when accessing the site through a Linux machine, with a browser that has JavaScript enabled.

**Comment by videosmith** [comment]
Are there .deb builds I can install?

**Comment by Cuperino** [comment]
I'll see if I can make one for x86_64 tomorrow.

**Comment by Cuperino** [comment]
I've uploaded a Deb for x86_64: https://sourceforge.net/projects/qprompt/files/v1.1.3/qprompt-v1.1.3-aa79ad5-linux-gcc-x86_64.deb/download

**Comment by videosmith** [comment]
Will try that, thank you.  As for the other packages:
Flatpak produced an error "Failed to install file: not supported"
Snap produced a command line error "This application failed to start because no Qt platform plugin could be initialized"
Possibly due to my ignorance of these delivery approaches, I will look into it.

**Comment by videosmith** [comment]
No delay in qprompt-v1.1.3-aa79ad5-linux-gcc-x86_64.deb build
![about](https://user-images.githubusercontent.com/88691671/213361804-f295c18b-c8ed-4c44-a72b-d51856b3845f.png)

**Comment by videosmith** [comment]
The delay appears to have disappeared with the 1.1.4 update.

**Comment by Cuperino** [comment]
That's very strange... Did you test using the AppImage?

**Comment by videosmith** [comment]
My mistake.  Tested with the .deb install.

qprompt-v1.1.4-5801a58-linux-gcc-x86_64.Appimage will not run.

**Comment by Cuperino** [comment]
What does it say if you launch the AppImage from a terminal? Remember that the AppImage from Craft only supports x86_64, so won't run on a Pi.

**Comment by videosmith** [comment]
My mistake. Forgot to make AppImage executable :/

Yes, delay still exists in windowed mode.

**Comment by Cuperino** [comment]
Used to happen to me all the time...

I figured it was probably that because I didn't changed anything that would affect the delay. Typically I make a new Craft install for each new build, but since the last one was less than a month old, and I didn't want to spend time fixing things if KDE broke something, I only updated QPrompt's source and left everything else intact.

**Comment by Cuperino** [comment]
It's been a while since I last saw this issue occurring. Closing after 1.2 release if I don't get to experience it again after testing all of the supported builds.

**Comment by Cuperino** [comment]
I haven't had this issue in a looong time. It hasn't appeared in any of the Qt 6 builds. Closing for now, feel free to re-open.
