### ISSUE TITLE
Tool Tips hidden by menu

### ISSUE THREAD

**Issue by mbhs-scott** [Cuperino/QPrompt-Teleprompter#180]
**Bug Description**
Tool tips for the top menu items are hidden by the menu itself

**Steps to Reproduce**
1.Click on one of the menus across the top
2. Hover over one of the items
3. Tool tip explaining the feature is hidden behind the menu

**Expected behavior**
Tool tip to be in front of the menu to be visible to the user

**Detailed description of display configuration** (if applicable)
Windows laptop, 1920x1080, happens both in fullscreen mode and normal mode

**Screenshots** (optional)
![image](https://user-images.githubusercontent.com/125222443/236367809-290319b0-a141-4fcd-acd1-429705301c98.png)

**Device information**
 - QPrompt Version: 1.1.6 (V1.1/51788eb)
 - Operating System: Windows 10 22H2

**Additional context**

**Comment by Cuperino** [comment]
This bug lies upstream in the Kirigami framework, which is used to create QPrompt, and not in QPrompt itself. I'll leave the issue open for the record and reminders.

**Comment by Cuperino** [comment]
KDE community fixed it upstream
