### ISSUE TITLE
Search controls blocked by prompt button

### ISSUE THREAD

**Issue by videosmith** [Cuperino/QPrompt-Teleprompter#184]
**Steps to Reproduce**
1. On some scripts (not your welcome)
2. Set screen resolution to 720p
3. Copy shift-v text from a word doc
4. enter fullscreen editing mode
5. click magnifying glass to search
6. button is obscured

**Expected behavior**
Should display the same as 1080p

RPi 400 ubuntu 22.04 latest updates
Qprompt 1.2 ver. 5

![pic](https://github.com/Cuperino/QPrompt/assets/88691671/a6d465af-ab8f-429d-9e1c-705ecfa3d546)

**Comment by videosmith** [comment]
![20230518_130550](https://github.com/Cuperino/QPrompt/assets/88691671/4246d677-1e3b-49c3-9d39-6cbb1b052633)

**Comment by videosmith** [comment]
Understood. Why doesn't it occur with your Welcome script?
![20230518_151025](https://github.com/Cuperino/QPrompt/assets/88691671/db51b097-f542-4b65-907a-e4d412594ac4)

**Comment by Cuperino** [comment]
A bug in Kirigami causes the prompter to sometimes extend above the buttons
and sometimes bellow them. There’s probably a way to trigger this with my
script as well. Perhaps by leaving and re-entering full screen, or by
reloading my script after getting the prompter to extend behind the buttons.
-- 
Javier O. Cordero Pérez
Full Stack Web Developer
Qt Software Developer

**Comment by Cuperino** [comment]
Upstream removal of of these buttons from Kirigami's desktop mode means we can safely close this issue.
