### ISSUE TITLE
Prompt width

### ISSUE THREAD

**Issue by skiwithpete** [Cuperino/QPrompt-Teleprompter#238]
Just needs an adjustment for width

**Comment by Cuperino** [comment]
Hi @skiwithpete,

Thank you for writing. You can adjust the width of the prompter inside the editor by dragging the vertical line to the left of the text, and offset the text horizontally by dragging the line to the right of the text.

Here's a video showing this on a Linux phone, go to 0:42: https://twitter.com/JCuperino/status/1482379644716425222?s=42

I'm closing this issue as "already implemented". If you meant something else, feel free to re-open and please provide as much detail as you can.
