### ISSUE TITLE
Windows installer does not run on 32-bit devices

### ISSUE THREAD

**Issue by aquisio** [Cuperino/QPrompt-Teleprompter#250]
**Bug Description**

When the Windows installer is run on a 32-bit Windows device (an old Linx 10V32 tablet) it halts installation, with the message "QPrompt v1.1-51788eb   This installer can only be run on 64-bit Windows".

**Steps to Reproduce**
1. Download the latest Windows installer
2. Run it on a 32-bit Windows device
3. Grant permission for the app installer to make changes to the Windows device
4. Wait for an error dialog to be displayed

**Expected behavior**

The installer should run to completion.

**Device information**
 - QPrompt Version: v1.1-51788eb
 - Operating System: Windows 10
 - Hardware: Linx 10V32

**Additional context**

My assumption that this installer should run on a 32-bit device is based on the **x86** in installer filename: qprompt-v1.1.6-51788eb-windows-cl-msvc2019-x86_64. If this is only intended for 64-bit hardware, can you please clarify? Thanks.

**Comment by aquisio** [comment]
Thanks @Cuperino for your really quick response, and thanks also for explaining the naming convention used in the download file.

I don't think it's within my skill set to resolve build issues and create an x86 platform installer, so I guess I'll have to get some newer hardware :)

In any case QPrompt is a great product and I appreciate all the work that has gone into creating it. Thank you.

**Comment by Cuperino** [comment]
If budget is a concern, consider getting a Raspberry Pi 5 to use with your teleprompter. It's energy efficient and uses the arm64 architecture, which is officially supported under Linux. You could also do with a Raspberry Pi 4, but your display resolution will be limited to 720. The Pis will work swell for prompting to a single screen.

If you need to use multiple teleprompters at the same time, the professional approach is to get a quality HDMI splitter, such as the hardware from Decimator.com. If a splitter is not an option, you can use the Screen feature included in QPrompt, but you'll need a fast computer that can handle it. It's generally cheaper to get dedicate a low spec computer (such as the Raspberry Pi), and combine it with a modest HDMI splitter.

Keep in mind that only Linux builds of QPrompt and Imaginary Teleprompter are supported on the Raspberry Pi; there are no arm64 Windows builds at the time.

For further tech support regarding setups, consider joining our [Telegram group](https://t.me/imaginaryteleprompter) where the users community can also help. I'll be closing this issue for now. Thank you for writing!
