### ISSUE TITLE
Importing text data from a html webpage 

### ISSUE THREAD

**Issue by Taz2000** [Cuperino/QPrompt-Teleprompter#254]
Hi, i'm looking to use qprompt on my raspberry pi for live outside broadcasts. 

I'd like to be able to edit the show scripts from home via a webpage, then the Pi can boot up and automatically load qpromt in full screen mode and pull text data from the webpage straight away. 

I'd also like to be able to change text on the webpage then refresh the program so that the text in qprompt has updated. 

In terms of a solution, id need qpromt to be able to direct its input from a web address and boot into full screen on boot. Also, an input to refresh so that qpromt can pull data from the webpage again if it has changed. 

Let me know what you think :)

**Comment by Cuperino** [comment]
Hi @Taz2000 please use this medium only to file bug reports and specific feature requests. You must create a separate issue for bug report and each request.

For tech support and guidance on how to file issues, please use our forum at forum.cuperino.com or community chat spaces at Discord and Telegram. Links can be found at https://qprompt.app

Thanks for helping us keep the issue tracker organized.

**Comment by Cuperino** [comment]
Potential feature request might be a duplicate of https://github.com/Cuperino/QPrompt-Teleprompter/issues/143, which has been implemented and is already available from early access builds.
