### ISSUE TITLE
LibreOffice not found when using LibreOffice Portable on Windows

### ISSUE THREAD

**Issue by ChrigiGee** [Cuperino/QPrompt-Teleprompter#257]
**LibreOffice not visible for QPrompt**

Sometimes by QPromt and RTF Files I have an Error, LO not exist, or found.
Picture below.

**Bug Description**
I open an RTF File with my Script and wait its opening....

**Steps to Reproduce**
1. Open File
2.RTF File Extension
3.QPromt not find LO
4. if I check, LO source exist in QP.

**Screenshots** (optional)

![Image 2024-06-04=1717510328](https://github.com/Cuperino/QPrompt-Teleprompter/assets/1215270/eb162e18-2c5b-4982-a270-4177f3c4a761)

![Image 2024-06-04=1717510237](https://github.com/Cuperino/QPrompt-Teleprompter/assets/1215270/550c844f-027e-4698-a27d-ad6d92c8066d)

**Device information**
 - QPrompt Version: 1.2 beta 6
 - Operating System: Windows 11 - 64 Bit

Has someone other of you this feature seen ?
And big sorry to my English, it's not my native Language and I never learn.

Kind regards
Chris

**Comment by Cuperino** [comment]
This sounds like a bug. I haven't tried this feature with LibreOffice Portable before.

> Has someone other of you this feature seen ?
@videosmith had a similar issue once before, but I doubt that it relates to this.

@ChrigiGee Does this also happen with ODT and DOCX files?

**Comment by ChrigiGee** [comment]
Hi Javier,
THX for your Input.
I don't try it, but I will start a test with the other Doc formats.
I can send you again update soon.

Kind regards
Christian

**Comment by Cuperino** [comment]
Thanks. Take your time, I will look at this issue over the weekend.

**Comment by Cuperino** [comment]
It took me a while to get to test this, but I'm unable to replicate this issue using the latest development build and one of the latest LibreOffice Portable build. I'm going to close the issue, feel free to re-open if this happens again on v2.0 or later.

My path to LibreOffice was: `C:/Users/Cuperino/Downloads/LibreOfficePortable/App/libreoffice/program/soffice.exe`
