### ISSUE TITLE
MacOS installer failed with corupted file error

### ISSUE THREAD

**Issue by blazevivan** [Cuperino/QPrompt-Teleprompter#260]
**Are you ready to report?**

Before reporting a bug, use GitHub's [issues filter](https://github.com/Cuperino/QPrompt/issues) to see if the bug you've found was already reported. If it has been reported, please indicate said bug also affects you and provide details that add value to the discussion. If the bug hasn't been reported, please continue to fill out this form.

**Bug Description**
The MacOS installer failed with a corrupted file error

**Steps to Reproduce**
1. Download the installation file
2. Run installer
3. See the error

**Expected behavior**
Install the app without issues

**Detailed description of display configuration** (if applicable)

**Screenshots** (optional)
![Error - 240618172035](https://github.com/Cuperino/QPrompt-Teleprompter/assets/13187242/b4bf2e99-debd-4cfd-bb7f-d27369c31fc2)

**Device information**
 - QPrompt Version: v1.1.6-51788eb-macos-clang-x86_64
 - Operating System: MacOs Sonoma 14.5

**Additional context**

**Comment by Cuperino** [comment]
Hi @blazevivan,

This issue has already been reported. Please read the original report for information on how to work around the issue if you'd like to run one of the versions that face this issue on MacOS: https://github.com/Cuperino/QPrompt-Teleprompter/issues/150

We're in the process of re-creating our entire build pipeline. The latest status report on this can be found in our public Patreon blog: https://www.patreon.com/posts/106234846

**Comment by Cuperino** [comment]
https://github.com/Cuperino/QPrompt-Teleprompter/issues/150#issuecomment-1416922130
