### ISSUE TITLE
Portuguese translations

### ISSUE THREAD

**Issue by hugok79** [Cuperino/QPrompt-Teleprompter#264]
* Currently the Portuguese translations at https://l10n.cuperino.com/languages/pt/qprompt/ are translated into the Brazilian variant of Portuguese/Portuguese (Brazil)/Brazilian Portuguese or whatever you want to call it.
* Nevertheless, the `pt` lang code relates to Portuguese of Portugal so should be a distinction between both languages

* Portugal = `pt` or `pt_PT`
* Brazil = `pt_BR`

**Comment by Cuperino** [comment]
If I simply add the BR suffix, someone would need to create the Portugal variant of the translation from scratch. To reduce the amount of duplicate work what I can do instead is duplicate the Brazilian translation into both Portuguese codes. That way it'll be easier for the contributor willing to work on the Portugal variant to complete it.

**Comment by hugok79** [comment]
Hi @Cuperino
I'm willing to translate and complete the Portuguese (Portugal)

**Comment by Cuperino** [comment]
Awesome! I'll update the translation files with the latest changes to the codebase later this week and let you know as soon as this change is up.

**Comment by Cuperino** [comment]
That turned out to be less complicated than I had anticipated... The fix is up!

Pt_PT translation pages can now be found here:

- https://l10n.cuperino.com/projects/qprompt/qprompt-app/pt_PT/
- https://l10n.cuperino.com/projects/qprompt/qprompt-welcome/pt_PT/
