### ISSUE TITLE
Fontello failing to load on Australian Windows 10 system

### ISSUE THREAD

**Issue by Cuperino** [Cuperino/QPrompt-Teleprompter#268]
**Bug Description**
[Jeff61](https://forum.cuperino.com/u/Jeff61) shared this image on the forum: https://forum.cuperino.com/uploads/default/original/1X/d4ad26a5a672b202e04cad7a6844a7c84a0a2cd3.jpeg

This shows QPrompt v1.1.6 unable to load its Fontello fonts. 

**Steps to Reproduce**
We don't have steps to reproduce the issue.

**Expected behavior**
Fontello icons load and show properly

**Screenshots** (optional)
![1c3e7bf7da430bd0219fd6d68c0be7dfdea355d8](https://github.com/user-attachments/assets/c71eb9bb-7a6b-4ad6-878e-69dc1c6550a2)
![d4ad26a5a672b202e04cad7a6844a7c84a0a2cd3](https://github.com/user-attachments/assets/dcbed7e7-6e2f-4cb1-ad82-eaea4ad639a2)

**Device information**
 - QPrompt Version: v1.1.6
 - Operating System: Windows 10

**Additional context**
https://forum.cuperino.com/t/why-do-i-have-chinese-characters-on-the-app/141/3

**Comment by Cuperino** [comment]
I have Windows 11, so I've tried the following:

- Set it to Australian English and deleted US English.
- Set the Current System Locale to Australia.
-  Enable “Beta: Use Unicode UTF-8 for Worldwide language support”.
- Set all normal Windows 11 themes.
- Set all Windows 11 Accessibility / High Contrast themes.
- Changed default Windows system font from Segoe UI to Comic Sans MS by means of a registry change.

With each of those changes QPrompt continued to work as expected, even after restarting. This leads me to believe this issue might only affect Windows 10 and earlier.

No other users from Australia have complained about this issue. This leads me to suspect this issue might not be related to the fact that Windows is set to Australian English.

**Comment by Liebeg** [comment]
I could try something on my Windows 10 install. Just have to let me know what i should test.

**Comment by Cuperino** [comment]
I'd wait to see how the new v2.0 build works for Jeff. Qt 6 changes how text encoding is done in Windows by making use of Unicode pretty much everywhere. There's a good chance it just might work correctly out of the box.

**Comment by Cuperino** [comment]
Closing issue as we're unable to reproduce it at this point. Anyone, feel free to re-open if it happens to you on the latest versions of QPrompt.
