### ISSUE TITLE
Alternating text/background colour while prompting

### ISSUE THREAD

**Issue by Liebeg** [Cuperino/QPrompt-Teleprompter#269]
**Is your feature request related to a problem or a limitation? Please describe...**
When speeding the prompter up its possible to loose the right line. 

**Describe the solution you'd prefer**
I would prefer the option to enable interlaced text colors. So line one is white line to is brown and line three white again.

**Describe alternatives you've considered**
I haven't consider alternatives.

**Provide use examples**
It alows to easier keep track of wich line you are currently reading.

**Comment by videosmith** [comment]
Possible workaround:
Client creates document with alternating colored text.
Load document and save as <.html>.
Open <html> in browser (pagination issues if copied directly from word processor for me).
Copy/paste into QPrompt.
Adjust font/size preferences.
