### ISSUE TITLE
Replace All enters infinite loop when replace value contains search value

### ISSUE THREAD

**Issue by Cuperino** [Cuperino/QPrompt-Teleprompter#274]
**Bug Description**
Replace All enters infinite loop when replace value contains search value

**Steps to Reproduce**
1. Set find value to QPrompt
2. Set replace value to QPrompt
3. Press Replace All

Alternatively

1. Set find value to an
2. Set replace value to and
3. Press Replace All

**Expected behavior**
Values get replaced and input is returned to the used.

**Device information**
 - QPrompt Version: 1.1.6
 - Operating System: All

**Comment by er3eck** [comment]
I personally prefer the font size control to be entered numerically....

**Comment by Cuperino** [comment]
Dully noted.

I link to the appropriate discussion here, so this conversation appears as referencing that one:
https://github.com/Cuperino/QPrompt-Teleprompter/issues/305
