### ISSUE TITLE
[ALL ?] texts for translation missing [LOCATION]

### ISSUE THREAD

**Issue by karls0** [Cuperino/QPrompt-Teleprompter#278]
**Are you at the right place?**
QPrompt translations are made by a community of people from around the world of which you could be a part of. Before filling out this form, you should visit [https://l10n.cuperino.com](https://l10n.cuperino.com/projects/qprompt-app/qprompt/), where you'll have tools to propose and submit your changes, and take credit for your contributions. Contributions made through this form won't be accredited to those who submit them, instead the credit will go to the maintainers who make those changes over at: [https://l10n.cuperino.com](https://l10n.cuperino.com/projects/qprompt-app/qprompt/)

**Which language is the translation error in?**
 - Language: all
 - Country Variant:
 - Region (optional):

**Steps to locate translation error**
1. window title “Scroll throttle settings” is not in l10n.cuperino.com...... as well as tool tips for “READING REGION”, “INDICATORS” and all menu titles, items and states.
2.
3.

**What is the translation error?**
parts of the programs UI are not in l10n.cuperino.com...... for translation

**What makes your suggestion a better translation?**

**Screenshot (optional)**

**System information**
 - QPrompt Version:  1.1.6
 - Operating System: Linux Mint 22

Find QPrompt's version number in the "About QPrompt" page.

**Comment by Cuperino** [comment]
Hey @karls0, Are you sure these things are missing on all languages? I was just able to locate “Scroll throttle settings”: https://l10n.cuperino.com/translate/qprompt/qprompt-app/es/?q=Scroll+throttle+settings&sort_by=-priority%2Cposition&checksum=

**Comment by Cuperino** [comment]
Here it is in German: https://l10n.cuperino.com/translate/qprompt/qprompt-app/de/?checksum=700a3065a85166a9

**Comment by karls0** [comment]
The menu item is in translations, but if you click on it a window opens and that windows title is not in translations. 
I suppose that the phrases, that need translation are automatically fed to the translation system the other items mentioned should be missing there too.

**Comment by karls0** [comment]
Sounds good, but although a lot of things are in German on my QPrompt, this window title isn't. Inside the window the first phrase is in German, everything else in English. see screenshot 


Mit freundlichen Grüßen 

i.A. Ing. Karl SCHUH 
Büro Bernstein 
Hauptstrasse 23a 
A-7434 Bernstein 
+43(664)3806107 

SCHUH-TV Filmproduktion 
Inhaber: Ing. Rene SCHUH 
FN: 160498b; Firmenbuchgericht: Handelsgericht Wien 
Wiedner Hauptstrasse 135/33 
A-1050 Wien 
+43(664)3363108 
http://www.schuh-tv.at 
E-mail ***@***.*** 


Von: "Javier O. Cordero Pérez" ***@***.***> 
An: "Cuperino/QPrompt-Teleprompter" ***@***.***> 
CC: "Karl SCHUH" ***@***.***>, "Mention" ***@***.***> 
Gesendet: Sonntag, 15. September 2024 17:21:10 
Betreff: Re: [Cuperino/QPrompt-Teleprompter] [ALL ?] texts for translation missing [LOCATION] (Issue #278) 





Each string that needs translation needs to be specified as such in the code. If two translations are identical, they get consolidated into one. 

That title for the window you mentioned is using: [ https://l10n.cuperino.com/translate/qprompt/qprompt-app/de/?checksum=43c1ea7d81660b0a | https://l10n.cuperino.com/translate/qprompt/qprompt-app/de/?checksum=43c1ea7d81660b0a ]

**Comment by karls0** [comment]
Mit freundlichen Grüßen 

Ing. Karl SCHUH 
Hauptstrasse 23a 
A-7434 Bernstein 
+43(664)3806107 


Von: "Javier O. Cordero Pérez" ***@***.***> 
An: "Cuperino/QPrompt-Teleprompter" ***@***.***> 
CC: "Karl SCHUH" ***@***.***>, "Mention" ***@***.***> 
Gesendet: Sonntag, 15. September 2024 17:21:10 
Betreff: Re: [Cuperino/QPrompt-Teleprompter] [ALL ?] texts for translation missing [LOCATION] (Issue #278) 





Each string that needs translation needs to be specified as such in the code. If two translations are identical, they get consolidated into one. 

That title for the window you mentioned is using: [ https://l10n.cuperino.com/translate/qprompt/qprompt-app/de/?checksum=43c1ea7d81660b0a | https://l10n.cuperino.com/translate/qprompt/qprompt-app/de/?checksum=43c1ea7d81660b0a ]

**Comment by Cuperino** [comment]
Oh, that's because you're using v1.1.6, which ships with the translations that were available at the time v1.1.6 was released, which is over a year ago. Since then Liebeg, other contributors, and you have added expanded the German translation to include those missing strings.

**Comment by Liebeg** [comment]
Kinda waiting to see the translations live

Javier O. Cordero Pérez ***@***.***> schrieb am So., 15. Sep.
2024, 17:46:

**Comment by Cuperino** [comment]
Ideally we'd have an online version of QPrompt made with WebAssembly that updates every time a change is made to the translations. That will have to wait until KDE Frameworks can be built with WebAssembly.

**Comment by Cuperino** [comment]
Closing for now. Feel free to re-open if there are untranslated strings for the German language in the next release.
