### ISSUE TITLE
[ENGLISH] better wording suggestion: Invert scroll direction => Invert mouse wheel

### ISSUE THREAD

**Issue by karls0** [Cuperino/QPrompt-Teleprompter#279]
**Are you at the right place?**

QPrompt translations are made by a community of people from around the world of which you could be a part of. Before filling out this form, you should visit [https://l10n.cuperino.com](https://l10n.cuperino.com/projects/qprompt-app/qprompt/), where you'll have tools to propose and submit your changes, and take credit for your contributions. Contributions made through this form won't be accredited to those who submit them, instead the credit will go to the maintainers who make those changes over at: [https://l10n.cuperino.com](https://l10n.cuperino.com/projects/qprompt-app/qprompt/)

**Which language is the translation error in?**
 - Language: ENGLISH
 - Country Variant:
 - Region (optional):

**Steps to locate translation error**
1. these are suggestions for a better wording:
2. Keyboard Inputs  => Key Mappings ...		
	Main menu and global menu actions. Opens dialog to configure keyboard inputs. 
        I think this better tells what it is for.
3.Invert scroll direction  => invert mouse wheel	
	 Main menu    since most people will think of the direction of the prompted text
4.

**What is the translation error?**
only suggestions

**What makes your suggestion a better translation?**
menu items will be clearer for users

**Screenshot (optional)**

**System information**
 - QPrompt Version: 1.1.6
 - Operating System: Linux Mint 22

Find QPrompt's version number in the "About QPrompt" page.

**Comment by Cuperino** [comment]
My only issue with invert mouse wheel is that it assumes the person is using a mouse. Many users make use of the prompter from a laptop and they don't all attach a mouse to it.

**Comment by karls0** [comment]
I get your point, but I think most people would understand the meaning. Also, I think, "scroll direction" refers to scrolling the text that is prompted. At least this was my assumption when trying QPrompt first without a manual.

**Comment by Cuperino** [comment]
I've gone with a different solution and instead added "(Natural scrolling)" to the existing text to help make it clearer. This is  the way developers of the KDE Plasma Desktop Environment chose to deal with this problem, which in this case helps QPrompt keep close to KDE human interface guidelines by making a statement that is true at all times while simultaneously providing additional information to make that statement a bit clearer.
