### ISSUE TITLE
key "i" in "edit while prompting" not working correctly

### ISSUE THREAD

**Issue by karls0** [Cuperino/QPrompt-Teleprompter#280]
**Are you ready to report?**

Before reporting a bug, use GitHub's [issues filter](https://github.com/Cuperino/QPrompt/issues) to see if the bug you've found was already reported. If it has been reported, please indicate said bug also affects you and provide details that add value to the discussion. If the bug hasn't been reported, please continue to fill out this form.

**Bug Description**
When you are in "edit while prompting mode" and want to insert an "i", the direction of the scrolling changes.

**Steps to Reproduce**
1.start prompting a text
2.double click in the text
3.type "i"

**Expected behavior**
character "i" should be written at the cursor

**Detailed description of display configuration** (if applicable)

**Screenshots** (optional)

**Device information**
 - QPrompt Version: 1.1.6
 - Operating System: Linux Mint 22

**Additional context**

**Comment by Cuperino** [comment]
Fix depends on #281 ro be fixed first.
