### ISSUE TITLE
Ctrl+PgDown does not work

### ISSUE THREAD

**Issue by karls0** [Cuperino/QPrompt-Teleprompter#283]
**Are you ready to report?**

Before reporting a bug, use GitHub's [issues filter](https://github.com/Cuperino/QPrompt/issues) to see if the bug you've found was already reported. If it has been reported, please indicate said bug also affects you and provide details that add value to the discussion. If the bug hasn't been reported, please continue to fill out this form.

**Bug Description**
Ctrl+PgDown does not jump to next marker, Ctrl+PgUp jumps to previous

**Steps to Reproduce**
1. set a few markers in your text
2. start prompting
3. try to jump to these markers with Ctrl+PgDown
4.

**Expected behavior**
jump to next marker for every keystroke

**Detailed description of display configuration** (if applicable)

**Screenshots** (optional)

**Device information**
 - QPrompt Version: 1.1.6
 - Operating System: Linux Mint 22

**Additional context**

**Comment by Cuperino** [comment]
I haven't tried this on Mint Cinnamon yet, but preliminary tests on KDE Plasma, using both the master branch and the stable version v1.1.6, show Ctrl+PgDown is working as intended. The issue could be that there's a Ctrl+PgDown shortcut present in Linux Mint's Cinnamon desktop that's grabbing onto the key combination, preventing the input event from reaching QPrompt.
