### ISSUE TITLE
Is there any advantage to running QPrompt on a Raspberry Pi 4b or 400

### ISSUE THREAD

**Issue by videosmith** [Cuperino/QPrompt-Teleprompter#84]
Is there any advantage of using your app between a Raspberry Pi 4b or 400?

**Comment by Cuperino** [comment]
I should add:

At present, all versions of QPrompt provide the same set of capabilities, except for the Android version, which offers less due to limitations of the Android platform.

The main advantage to running QPrompt on a Linux arm device is these devices spend less energy and, in most cases, they are cheaper than their x86_64 counterparts. ARM devices are also more portable, making them good to take with your teleprompter.

**Comment by videosmith** [comment]
fyi: i chose the Pi due to it's dual hdmi capability, useful in clone mode for QPrompt.

    On Tuesday, April 12, 2022, 07:17:25 PM EDT, Javier O. Cordero Pérez ***@***.***> wrote:  
 
 


Hi @videosmith,

Please use the forum for questions and use GitHub to report issues and request features. I check both places daily. The forum can be found at forum.cuperino.com. The advantage of using the forum is you provide people with the same questions an easy place to find the answer.

Onto the answer

The Raspberry Pi 400 has a slightly overclocked CPU because it can dissipate heat more easily thanks to its greater surface area. This makes it slightly better for an CPU and GPU intensive program like QPrompt. Apart from the raw speed, QPrompt will run just the same on any arm64 device that can run a modern Linux distro with graphics acceleration.

There are more powerful arm64 devices than the Raspberry Pi that are energy efficient and still cheaper than typical computers. For this reason, if you're looking to upgrade from your Raspberry Pi or adding another teleprompter, I recommend looking for alternatives that offer faster CPU and GPU clock speeds than the Raspberry Pi 400.

ODROID, from Hardkernel, is a brand that consistently produces arm64 computers that are typically faster than the most current Raspberry Pi generation. A few years ago I would also recommend the Nvidia Jetson Nano for Imaginary Teleprompter but I no longer do because Nvidia's custom version of Ubuntu is incredibly outdated (based of Ubuntu 18.04) and QPrompt's Qt dependencies can't be met on that device.

**Comment by videosmith** [comment]
My apologies and thank you.

    On Tuesday, April 12, 2022, 07:17:25 PM EDT, Javier O. Cordero Pérez ***@***.***> wrote:  
 
 


Hi @videosmith,

Please use the forum for questions and use GitHub to report issues and request features. I check both places daily. The forum can be found at forum.cuperino.com. The advantage of using the forum is you provide people with the same questions an easy place to find the answer.

Onto the answer

The Raspberry Pi 400 has a slightly overclocked CPU because it can dissipate heat more easily thanks to its greater surface area. This makes it slightly better for an CPU and GPU intensive program like QPrompt. Apart from the raw speed, QPrompt will run just the same on any arm64 device that can run a modern Linux distro with graphics acceleration.

There are more powerful arm64 devices than the Raspberry Pi that are energy efficient and still cheaper than typical computers. For this reason, if you're looking to upgrade from your Raspberry Pi or adding another teleprompter, I recommend looking for alternatives that offer faster CPU and GPU clock speeds than the Raspberry Pi 400.

ODROID, from Hardkernel, is a brand that consistently produces arm64 computers that are typically faster than the most current Raspberry Pi generation. A few years ago I would also recommend the Nvidia Jetson Nano for Imaginary Teleprompter but I no longer do because Nvidia's custom version of Ubuntu is incredibly outdated (based of Ubuntu 18.04) and QPrompt's Qt dependencies can't be met on that device.
